CI: Check Helm chart version already on registry before push,  update appVersion in Chart.

diff --git a/.github/workflows/publish-helm-chart.yaml b/.github/workflows/publish-helm-chart.yaml
--- a/.github/workflows/publish-helm-chart.yaml
+++ b/.github/workflows/publish-helm-chart.yaml
@@ -2,16 +2,8 @@ name: Build and publish helm chart
 
 on:
   push:
-    branches:
-      - 'main'
-    tags:
-      - "v*.*.*"
     paths:
       - 'charts/oss-catalog/**'
-
-env:
-  REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}
 
 jobs:
   build_and_publish_helm_chart:
@@ -36,8 +28,27 @@ jobs:
           helm dependency update ./charts/oss-catalog
           helm lint ./charts/oss-catalog
           helm package ./charts/oss-catalog
+
+      - name: Check helm chart version on registry
+        run: | 
+          VERSION=$(helm show chart charts/oss-catalog | grep "^version:" | cut -d ':' -f 2)
+          echo "Check chart with version v${VERSION} is not already on ghcr.io..."
+          helm show chart oci://ghcr.io/${{ github.repository_owner }}/oss-catalog --version $VERSION 2> /dev/null
+          if [ $? == 0 ]; then
+            echo "...chart version is already on ghcr.io."
+            echo "version_on_registry=1" >> "$GITHUB_ENV"
+          else
+            echo "...version not on ghcr.io."
+            echo "version_on_registry=0" >> "$GITHUB_ENV"
+          fi        
           
       - name: Push Helm Chart
+        # Publish chart only on changes on main branch and if version does not exist on registry.
+        if: github.ref == 'refs/heads/main'
         run: | 
+          if [ $version_on_registry != 0 ]; then
+            echo "Failed: Chart version is already on ghcr.io!"
+            exit 1
+          fi
           echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
           helm push oss-catalog-chart-*.tgz oci://ghcr.io/${{ github.repository_owner }}/
